server:
  port: 8222  

spring:
  datasource:
    url: jdbc:h2:mem:employee
    username: skg
    password: @Test123$
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

#debug: true